all:
  hosts:
    host1:
      ansible_host: 1.2.3.4
      ansible_user: root
      prometheus_containers:
      - container_name: prom1
        version: v2.40.1
        exposed_port: 9090
        retention_time: 1d
      - container_name: prom2
        version: v2.39.2
        exposed_port: 9091
        retention_time: 15d
      - container_name: prom3
        version: v2.39.2
        exposed_port: 9092
        retention_time: 30d



              